### ISSUE TITLE
2020 2학기 웹 2주차 과제 제출

### ISSUE THREAD

**Issue by Joo-ra-n** [haedal-with-knu/WWW#41]
여기에 댓글로 이름, 학과, 학번, 그리고 레포 주소를 써주시면 됩니도.

ex) 김주원 전자공학부 201x117149
https://github.com/joo-ra-n

**Comment by dja314159** [comment]
박상헌 컴퓨터학부 2019115900
https://github.com/hun340312/Haedal_2020_2_Web

**Comment by donghy22** [comment]
이동현 경제통상학부 2015115781
https://github.com/donghy22/WebPractice

**Comment by 52future** [comment]
손자영 컴퓨터학부 2020113825

https://github.com/52future/0925-web1.git

**Comment by himodu** [comment]
이동건 컴퓨터학부 2020112267

https://github.com/himodu/Webpractice.git

**Comment by Qad00** [comment]
카드리딘 컴퓨터학부 2020111177

https://github.com/Qad00/WebHW.git

**Comment by hdddhdd** [comment]
최희정 컴퓨터학부 2020114670

https://github.com/hdddhdd/Profile

**Comment by offings** [comment]
김현진 컴퓨터학부 2018112277 

https://github.com/apple0626/Web_programming

**Comment by iougou03** [comment]
권해솔 컴푸터학부 2017116948

https://github.com/iougou03/Python-HaeDal.git

**Comment by huihuiwon** [comment]
조희원 컴퓨터학부 2018110380
https://github.com/njhw20/haedal_prac

**Comment by gaarden** [comment]
문정원 컴퓨터학부 2020110975
https://github.com/gaarden/web1st

**Comment by heohyeonjin** [comment]
허현진 컴퓨터학부 2019110847
https://github.com/heohyeonjin/web1

**Comment by kayoung0** [comment]
김가영 컴퓨터학부 2019113963
https://github.com/kayoung0/haedal-web

**Comment by rtyui564** [comment]
김형준 전자공학부 2016110623
https://github.com/rtyui564/Haedal

**Comment by penguin123-pi** [comment]
이현중 전자공학부 2019113608
https://github.com/penguin123-pi/Web-practice

**Comment by gyeongpyo** [comment]
옥경표 컴퓨터학부 2018117630
https://github.com/gyeongpyo/practice/blob/master/web/w2.html

**Comment by choimyungbin** [comment]
최명빈 컴퓨터학부 2020111799
https://github.com/choimyungbin/practice_web

**Comment by bgainal** [comment]
신영진 전자공학부 2020111485 https://github.com/bgainal/pr/tree/master

**Comment by Sungbinbinbin** [comment]
조성빈 전자공학부 2020114669 https://github.com/Sungbinbinbin/Project

**Comment by hyunuk-2** [comment]
정현욱 전자공학부 2017114264
 https://github.com/hyunuk-2/practice

**Comment by hyunuk-2** [comment]
정현욱 전자공학부 2017114264 https://github.com/hyunuk-2/real-homework/blob/master/practice.html

**Comment by hyunuk-2** [comment]
정현욱 전자공학부 2017114264 https://github.com/hyunuk-2/practice

**Comment by hyunuk-2** [comment]
정현욱 전자공학부 2017114264  https://github.com/hyunuk-2/homework

**Comment by halnigalni** [comment]
서하린 컴퓨터학부 2018116308
https://github.com/Seoharin/-

**Comment by Lemontrace** [comment]
조상형 컴퓨터학부 2020111439
https://github.com/Lemontrace/haedal_web_1

**Comment by yanghuijin1214** [comment]
양희진 컴퓨터학부 2018111062 https://github.com/yanghuijin1214/web-haedal

**Comment by ByungHo-Jung** [comment]
정병호 모바일공학과 2017111584 
https://github.com/ByungHo-Jung/my-introduction-website-

**Comment by yxxniverse** [comment]
서정윤 컴퓨터학부 2019113288
https://github.com/yxxniverse/HAEDAL_webassign1

**Comment by Sowon-Kim** [comment]
김소원 컴퓨터학부 2018112817
https://github.com/Sowon-Kim/Sowon

**Comment by khj1030** [comment]
김현지 컴퓨터학부 2020111395
https://github.com/khj1030/haedal_web

**Comment by ezzez** [comment]
김은정 컴퓨터학부 2020112393
https://github.com/ezzez/headal_web

**Comment by TaeHeonKim250** [comment]
김태헌 전자공학부 2016110604
https://github.com/TaeHeonKim250/TaeHeonKim
