### ISSUE TITLE
2020 2학기 웹 4주차 과제 제출

### ISSUE THREAD

**Issue by LJBang** [haedal-with-knu/WWW#45]
2, 3주차에서 만든 웹에다 배운 CSS를 적용하여 코드와 웹화면을 캡쳐한뒤 함께 제출해주시면 됩니다!

**Comment by iougou03** [comment]
![image](https://user-images.githubusercontent.com/53176902/98835537-e5398580-2483-11eb-83c1-1a104095d988.png)

https://github.com/iougou03/Python-HaeDal

**Comment by penguin123-pi** [comment]
![4주차 웹 과제(코드1)](https://user-images.githubusercontent.com/71762382/98918377-e4026a00-2510-11eb-848e-9a3963147d19.PNG)
![4주차 웹 과제(코드2)](https://user-images.githubusercontent.com/71762382/98918387-e664c400-2510-11eb-9f17-61c649cf6ee9.PNG)
![4주차 웹 과제(웹1)](https://user-images.githubusercontent.com/71762382/98918403-ec5aa500-2510-11eb-8b6f-14da184bb389.PNG)
![4주차 웹 과제(웹2)](https://user-images.githubusercontent.com/71762382/98918417-f086c280-2510-11eb-8137-31c342de78ee.PNG)
2019113608 전자공학부 이현중

**Comment by hyunuk-2** [comment]
![image](https://user-images.githubusercontent.com/72441356/98928009-955acd00-251c-11eb-9957-0dd234930bca.png)
https://github.com/hyunuk-2/homework
2017114264 전자공학부 정현욱

**Comment by dja314159** [comment]
![HD03](https://user-images.githubusercontent.com/62656584/98950999-0d38ef80-253d-11eb-874c-7d87044faceb.png)

https://github.com/hun340312/Haedal_2020_2_Web
2019115900 컴퓨터학부 글로벌소프트웨어융합전공 박상헌입니다!!

**Comment by himodu** [comment]
![sdf](https://user-images.githubusercontent.com/71763322/98985354-c7911c80-2566-11eb-8d43-fa56f6db0a97.PNG)
https://github.com/himodu/practice-Web.git
2020112267 컴퓨터학부 심컴 이동건입니다.

**Comment by kayoung0** [comment]
![web4코드1](https://user-images.githubusercontent.com/68316096/99022544-48233d80-25a6-11eb-9125-54cf6d1ce591.png)
![web4코드2](https://user-images.githubusercontent.com/68316096/99022555-4bb6c480-25a6-11eb-80ec-e9499bd85ca0.png)
![web4화면캡쳐](https://user-images.githubusercontent.com/68316096/99022560-4e191e80-25a6-11eb-93f0-099241fc74e0.png)
2019113963 컴퓨터학부 김가영

**Comment by khj1030** [comment]
![image](https://user-images.githubusercontent.com/69004675/99033748-f3d88780-25be-11eb-835d-4ac06c3a18eb.png)
![image](https://user-images.githubusercontent.com/69004675/99033760-f89d3b80-25be-11eb-9998-6c1564ef5997.png)
2020111395 컴퓨터학부 김현지

**Comment by yxxniverse** [comment]
![해달웹1](https://user-images.githubusercontent.com/71762611/99036586-4a48c480-25c5-11eb-9a18-cad30d740f52.JPG)
![해달웹2](https://user-images.githubusercontent.com/71762611/99036590-4b79f180-25c5-11eb-941b-767a4e1540e6.JPG)
![해달웹3](https://user-images.githubusercontent.com/71762611/99036592-4b79f180-25c5-11eb-9a90-51cfc2166ef0.JPG)

2019113288 컴퓨터학부 서정윤

**Comment by offings** [comment]
![capture](https://user-images.githubusercontent.com/39369255/99147668-21f4bf00-26c6-11eb-8ab6-25a40955debd.PNG)
![code](https://user-images.githubusercontent.com/39369255/99147670-2325ec00-26c6-11eb-8d5c-8602594049b9.PNG)
https://github.com/apple0626/Web_programming

2018112277 컴퓨터학부 김현진

**Comment by ezzez** [comment]
https://github.com/ezzez/headal_web
![4week code](https://user-images.githubusercontent.com/71763831/99256161-5304f900-2858-11eb-97ca-6ec1948cc145.png)
![4week](https://user-images.githubusercontent.com/71763831/99256159-51d3cc00-2858-11eb-9606-4990cf707a32.PNG)
![Uploading 4week code.png…]()

**Comment by huihuiwon** [comment]
![자기소개캡쳐](https://user-images.githubusercontent.com/50469773/99531487-2252ca00-29e6-11eb-9dd6-2213b26081bb.PNG)
![1](https://user-images.githubusercontent.com/50469773/99531491-241c8d80-29e6-11eb-8df9-8f4aede222e9.PNG)
![2](https://user-images.githubusercontent.com/50469773/99531493-241c8d80-29e6-11eb-975f-808d6ce8b644.PNG)
2018110380 컴퓨터학부 조희원
저번학기 4주차에 올렸었어요ㅠㅠ

**Comment by gaarden** [comment]
![웹 4주차 과제](https://user-images.githubusercontent.com/72001106/101919488-f8b84780-3c0d-11eb-9814-8f5a65a478f0.JPG)
2020110975 컴퓨터학부 문정원
https://github.com/gaarden/web1st

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/46036377/101941396-43948800-3c2b-11eb-9655-e75f0e3070de.png)
![image](https://user-images.githubusercontent.com/46036377/101941420-4b542c80-3c2b-11eb-8367-f9a01a6b39ff.png)
2020111799 컴퓨터학부 최명빈

**Comment by Sowon-Kim** [comment]
![4주차](https://user-images.githubusercontent.com/72599000/102489084-5c2ff280-40b0-11eb-8a72-ca6b5a9212f6.JPG)
![4주차1](https://user-images.githubusercontent.com/72599000/102489111-6225d380-40b0-11eb-8db3-6e72e0d7f1bd.JPG)
![4주차2](https://user-images.githubusercontent.com/72599000/102489118-6520c400-40b0-11eb-891c-77db8036b1cd.JPG)

2018112817 김소원
