### ISSUE TITLE
2020 2학기 웹 5주차 과제제출

### ISSUE THREAD

**Issue by horkheimer8** [haedal-with-knu/WWW#46]
4주차 과제 가지고, 반응형  웹으로 만들어보입시다!!

**Comment by iougou03** [comment]
![image](https://user-images.githubusercontent.com/53176902/99083930-9b7aa780-2609-11eb-82f0-ca85ce7adfca.png)

2017116948  권해솔

https://iougou03.github.io/introduce.html

**Comment by ezzez** [comment]
2020112393 김은정
![5week](https://user-images.githubusercontent.com/71763831/99291511-4a75e800-2883-11eb-9e69-970b1b0516c2.PNG)
https://github.com/ezzez/headal_web/blob/main/5week.html

**Comment by Lemontrace** [comment]
2020111439조이
https://github.com/Lemontrace/haedal_web
main.html이 (놀랍게도!)메인입니다.

**Comment by huihuiwon** [comment]
2018110380 컴퓨터학부 조희원
https://github.com/njhw20/haedal_prac/blob/master/11_18.html

**Comment by kayoung0** [comment]
2019113963 컴퓨터학부 김가영
https://github.com/kayoung0/haedal-web

**Comment by penguin123-pi** [comment]
2019113608 전자공학부 이현중
https://github.com/penguin123-pi/Web-practice/blob/master/5%EC%A3%BC%EC%B0%A8%20%EC%9B%B9%20%EA%B3%BC%EC%A0%9C.html

**Comment by horkheimer8** [comment]
> ![image](https://user-images.githubusercontent.com/53176902/99083930-9b7aa780-2609-11eb-82f0-ca85ce7adfca.png)
> 
> 2017116948 권해솔

**Comment by hyunuk-2** [comment]
2017114264 전자공학부 정현욱
https://github.com/hyunuk-2/homework

**Comment by gaarden** [comment]
2020110975 컴퓨터학부 문정원
https://github.com/gaarden/web1st

**Comment by khj1030** [comment]
2020111395 컴퓨터학부 김현지
https://github.com/khj1030/haedal_web

**Comment by himodu** [comment]
반응형웹.html

**Comment by himodu** [comment]
2020112267 컴퓨터학부 이동건
https://github.com/himodu/practice-Web.git

**Comment by Sowon-Kim** [comment]
2018112817 컴퓨터학부 김소원
https://github.com/Sowon-Kim/Sowon
