### ISSUE TITLE
2020 2학기 웹 6주차 과제제출

### ISSUE THREAD

**Issue by LJBang** [haedal-with-knu/WWW#48]
이번에는 스샷이 아니라 깃헙페이지 주소를 남겨주세요!
예시) http://ljbang.github.io (저는 꾸미지 않았군요..)

**Comment by penguin123-pi** [comment]
2019113608 이현중
https://github.com/penguin123-pi/penguin123-pi.github.io

**Comment by penguin123-pi** [comment]
2019113608 전자공학부 이현중
http://localhost:63342/pythonProject16/penguin123-pi.github.io/assets/index.html?_ijt=66spgelgd2lb557va26ram05ae

**Comment by penguin123-pi** [comment]
2019113608 전자공학부 이현중
http://localhost:63342/pythonProject16/penguin123-pi.github.io/assets/index.html?_ijt=kqdqrjog3hbb0jgdp3k4gj3r5d

**Comment by penguin123-pi** [comment]
2019113608 전자공학부 이현중
http://localhost:63342/pythonProject16/penguin123-pi.github.io/assets/index.html?_ijt=psuogl1hris4fldf4lvl43afta

**Comment by penguin123-pi** [comment]
2019113608 전자공학부 이현중
http://localhost:63342/pythonProject16/penguin123-pi.github.io/assets/index.html?_ijt=g61n7k5tn8iqod1dt5ft9a00au

**Comment by penguin123-pi** [comment]
2019113608 전자공학부 이현중
http://localhost:63342/pythonProject18/penguin123-pi.github.io/assets/index.html?_ijt=kg6ukjc1mck3hj76502ndhcptj

**Comment by iougou03** [comment]
2017116948 글솦 권해솔
https://iougou03.github.io/

**Comment by offings** [comment]
2018112277 컴퓨터학부 김현진
https://github.com/apple0626/apple0626.github.io

**Comment by Lemontrace** [comment]
2020111439 글솦 조이
https://lemontrace.github.io/

**Comment by kayoung0** [comment]
2019113963 컴퓨터학부 김가영
https://kayoung0.github.io/

**Comment by himodu** [comment]
2020112267 컴퓨터학부 이동건
https://himodu.github.io/

**Comment by himodu** [comment]
2020112267 컴퓨터학부 이동건
https://himodu.github.io/

**Comment by huihuiwon** [comment]
2018110380 컴퓨터학부 조희원
https://njhw20.github.io/

**Comment by hyunuk-2** [comment]
2017114264 전자공학부 정현욱
http://hyunuk-2.github.io/portfolio.html

**Comment by khj1030** [comment]
2020111395 컴퓨터학부 김현지
repository에 올리는 데에 계속 실패해서 개인적으로 연락드렸습니다.
사진 첨부도 안되어 과제를 확인 받을 방법이 안 떠올라, 이렇게 제출하게 되었습니다. 죄송합니다.

**Comment by khj1030** [comment]
2020111395 컴퓨터학부 김현지
https://khj1030.github.io/

**Comment by ezzez** [comment]
2020112393 컴퓨터학부 김은정
https://ezzez.github.io/

**Comment by yxxniverse** [comment]
2019113288 컴학 서정윤
https://yxxniverse.github.io/

**Comment by yanghuijin1214** [comment]
2018111062 컴퓨터학부 양희진
https://yanghuijin1214.github.io/index.html

**Comment by Sowon-Kim** [comment]
2018112817 컴퓨터학부 김소원
https://github.com/Sowon-Kim/Sowon
