### ISSUE TITLE
2020 2학기 웹 7주차 과제제출

### ISSUE THREAD

**Issue by cometrue00** [haedal-with-knu/WWW#49]
Java Script의 Canvas를 이용해서 자신만의 눈사람을 만들고,
코드와 눈사람을 캡처한 뒤 함께 제출해주세요!

**Comment by offings** [comment]
![image](https://user-images.githubusercontent.com/39369255/101044028-486d9200-35c2-11eb-8b23-227477363a9d.png)
![image](https://user-images.githubusercontent.com/39369255/101044075-53282700-35c2-11eb-9fe6-3b0b0433c4de.png)
![image](https://user-images.githubusercontent.com/39369255/101044103-5a4f3500-35c2-11eb-9ae0-676ea437b25e.png)

컴퓨터학부 2018112277 김현진

**Comment by khj1030** [comment]
![스크린샷(6)](https://user-images.githubusercontent.com/69004675/101136491-bf516c00-3650-11eb-8c6b-debebed2bc01.png)
![스크린샷(7)](https://user-images.githubusercontent.com/69004675/101136494-c11b2f80-3650-11eb-8ad4-93823b283470.png)
2020111395 컴퓨터학부 김현지

**Comment by huihuiwon** [comment]
2018110380 컴퓨터학부 조희원
![snowman](https://user-images.githubusercontent.com/50469773/101136725-1a835e80-3651-11eb-8679-dab19af82791.PNG)
![12041651387751](https://user-images.githubusercontent.com/50469773/101136743-1f481280-3651-11eb-918b-53fcf4cc97ea.jpg)

**Comment by gaarden** [comment]
![웹 7주차 과제](https://user-images.githubusercontent.com/72001106/101925744-8d727380-3c15-11eb-8d87-852aecb7749a.JPG)
2020110975 컴퓨터학부 문정원

**Comment by Lemontrace** [comment]
2020111439조이
![Screenshot from 2020-12-15 22-15-09](https://user-images.githubusercontent.com/34397913/102219624-1134a480-3f23-11eb-9879-0bb00991eae2.png)
![Screenshot from 2020-12-15 22-12-00](https://user-images.githubusercontent.com/34397913/102219401-c4e96480-3f22-11eb-9713-ceb986fa631c.png)

**Comment by hyunuk-2** [comment]
2017114264 전자공학부 정현욱
![image](https://user-images.githubusercontent.com/72441356/102311048-8483f800-3faf-11eb-8ca0-9c1038b8bf5c.png)
![image](https://user-images.githubusercontent.com/72441356/102311069-8b126f80-3faf-11eb-98a8-6c97e9d39e29.png)
![image](https://user-images.githubusercontent.com/72441356/102311086-906fba00-3faf-11eb-9d18-3ba184c5e26f.png)
![image](https://user-images.githubusercontent.com/72441356/102311096-96659b00-3faf-11eb-9b7a-da0eafe0f0e5.png)

**Comment by yxxniverse** [comment]
2019113288 서정윤
![python_7_1](https://user-images.githubusercontent.com/71762611/102331909-c6706680-3fce-11eb-9111-90a6e9b7e9d6.JPG)
![python_7_2](https://user-images.githubusercontent.com/71762611/102331928-cb351a80-3fce-11eb-9b30-69f5dd0d83d3.JPG)
![python_7_3](https://user-images.githubusercontent.com/71762611/102331931-cc664780-3fce-11eb-8b3f-9e6042b09158.JPG)

**Comment by Sowon-Kim** [comment]
2018112817 김소원
![7주차1](https://user-images.githubusercontent.com/72599000/102487823-841e5680-40ae-11eb-9890-280d1fe50394.JPG)
![7주차2](https://user-images.githubusercontent.com/72599000/102487839-884a7400-40ae-11eb-8d9a-eea1cbf58221.JPG)
![웹7주차](https://user-images.githubusercontent.com/72599000/102487844-897ba100-40ae-11eb-8590-a56236234ea7.JPG)

**Comment by himodu** [comment]
![snowman](https://user-images.githubusercontent.com/71763322/102492251-c2b70f80-40b4-11eb-863c-3e5b67be30a0.PNG)
![1n](https://user-images.githubusercontent.com/71763322/102492256-c480d300-40b4-11eb-837e-5591c7231656.PNG)
![2n](https://user-images.githubusercontent.com/71763322/102492261-c5b20000-40b4-11eb-9616-c78ba5bc4759.PNG)
2020112267 이동건 컴퓨터학부
